# Generated by Django 2.1.5 on 2020-03-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20200321_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='wonder',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
    ]
