# Generated by Django 2.1.5 on 2020-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logInDate',
            field=models.DateField(null=True),
        ),
    ]
