# Generated by Django 2.1.5 on 2020-03-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20200313_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
